### PR TITLE
Support for react files (.jsx, .tsx)

### LINKED ISSUE #2: Only works on .js files?
Im trying to use it on a `.jsx` file and nothing....

How would I go about allowing it to work on those files?

Thanks.

### PR DESCRIPTION
**Pull request by rodrigograca31**
fixes #2

### CODE REVIEW

**Comment by rodrigograca31** [comment]
@vinliao can you please accept this PR?

**Comment by rodrigograca31** [comment]
Ping @vinliao

**Comment by vinliao** [comment]
Sorry for the late reply @rodrigograca31, I was pretty busy lately. I have merged the pr and deployed the new version.

**Comment by rodrigograca31** [comment]
Great! :heart:

**Pull request merged**
